### PR TITLE
fixed dependencies and added simple copy-pasted (original) examples f…

### PR DESCRIPTION
**Pull request by rsaccon**
…or all toolbox components.

So we have something simple right now, to see what works

### CODE REVIEW

**Comment by developit** [comment]
Awesome, will merge today :)

**Comment by developit** [comment]
Looks like this is my new component framework, haha.
I'm debating whether to keep the old index.js as a second bundle in order to keep measuring size. Think it's worth it?  For now I'll merge but it might be worth a look.

**Comment by rsaccon** [comment]
Ah, yes, I am sorry, the new dependencies probably kill your marketing slogan of 95% less filesize. When all components work we don't need this anymore and I am happy if you kick it out again.

**Comment by developit** [comment]
I was thinking we could just move the full examples into their own repo and have that be the docs for preact-toolbox :) 

I'm going to play around with Webpack 2's tree shaking to see what it does for the file size. 

So happy to have all these components visible though, very exciting.

**Pull request merged**
